### ISSUE TITLE
Adjust latency of typing detection

### ISSUE THREAD

**Issue by philffm** [leo-labs/VoodooSMBus#14]
Using the patch for a few hours now and and finally the interoperability with Touchpad and Trackpoint seems perfekt. 
However: Is there a way to adjust the latency of the typing detection? As I use key combanitions like CMD+TAB alot (also while using the mouse) but now the mouse gets stuck 1 second before it is usable again.

Thanks in advance!

Best, Phil

**Comment by kekkokk** [comment]
There's my ugly implementation if you want to try:
https://github.com/leo-labs/VoodooSMBus/pull/12

I think leo-labs it's going to rewrite in a decent way this module

**Comment by leo-labs** [comment]
@kekkokk @philffm Please checkout the newest release :)
