### ISSUE TITLE
Switching fingers while dragging will cancel dragging

### ISSUE THREAD

**Issue by yszhangyh** [leo-labs/VoodooSMBus#19]
When dragging a file, when the finger reaches the edge of the touchpad, the original finger is pressed against the touchpad, and when the other finger presses the center of the touchpad to continue dragging, the dragged file is released.

**Comment by leo-labs** [comment]
What dragging settings do you use in macOS? Tap to drag has its limitations in macOS, see https://voodooi2c.github.io/#Supported%20Gestures/Supported%20Gestures

I did not enable dragging in accessibility, but use the physical clickpad to drag files.

**Comment by leo-labs** [comment]
Closing this, as I did not here from you in two weeks now
