### ISSUE TITLE
Ignore input when keyboard is used

### ISSUE THREAD

**Issue by leo-labs** [leo-labs/VoodooSMBus#2]
Use the implementation at https://github.com/kprinssu/VoodooI2CELAN/blob/master/VoodooI2CELAN/VoodooI2CELANTouchpadDriver.cpp to ignore input when typing

**Comment by vistree** [comment]
Now it is the first time that I can use my t480s with gestures and at the same time write without interruption. I am totally thrilled! Good work man!!
