### ISSUE TITLE
VoodooPS2Controller still attaches itself to MOU

### ISSUE THREAD

**Issue by notthebee** [leo-labs/VoodooSMBus#21]
Firs of all, thanks for your amazing work!

I'm trying to install the kext on my Thinkpad X1 Carbon 6th gen which seems to have the same SMBus controller as T480s (`pci8086,9d23`).  
However, after following all the instructions, the touchpad and trackpoint still seem to be driven by VoodooPS2Controller – e.g. no gestures, trackpad input doesn't get ignored while typing on keyboard, etc.
According to IORegistryExplorer, the kext seems to be loading and there's an item called VoodooSMBusControllerDriver attached to SBUS. The trackpad menu in System Prefernces indicates full gesture support but none of them work.
![Screenshot 2019-12-05 at 13 08 31](https://user-images.githubusercontent.com/30384331/70234535-21874080-1761-11ea-99e0-4ad1f15e5faf.png)

I took a look at the MOU node in IORegistryExplorer and it seems like the VoodooPS2Controller is still attached to it. `PNP0F13` in `MouseNameMatch` seems to still be present despite the patch. I've tried removing it from VoodooPS2Controller.kext/Contents/Info.plist manually, however after that all the input devices (keyboard, trackpad, nub) would stop working altogether.
![Screenshot 2019-12-05 at 13 06 31](https://user-images.githubusercontent.com/30384331/70234550-2cda6c00-1761-11ea-8479-c67373a950cc.png)
If I just remove VoodooPS2Touchpad.kext plugin, the trackpad and the trackpoint stop functioning too.

**Comment by notthebee** [comment]
Disregard this issue. Looks like X1C6 has a Synaptics trackpad unlike T480s which comes with an ELAN model.

**Comment by leo-labs** [comment]
So how is the trackpad connected? What driver is used in linux?

**Comment by notthebee** [comment]
I haven't checked it on Linux, but since it's a Synapics touchpad, your SMBus driver will not work with it.
I've ordered a T480s touchpad from Aliexpress since the FRUs for T480s and X1C6 trackpads seem to be compatible. We'll see how that goes.

**Comment by leo-labs** [comment]
So from this (https://gitter.im/alexandred/VoodooI2C?at=5caa0c5da84e0c501aef8a4a) comment in the VoodooI2C gitter, it seems that the X1C6 actually uses the synaptics protocol via the SMBus. It this is true, then it is possible to add synaptics support to VoodooSMBus, similar as already multiple different protocols are supported via I2C: 
For SMBus/I2C devices there is always a main driver for the bus, that coordinates the communication of multiple slave devices, in our case just the trackpad. As you can see from the code in this project, the main driver is implemented in https://github.com/leo-labs/VoodooSMBus/blob/master/VoodooSMBus/VoodooSMBusControllerDriver.hpp and has the ability to publish nubs for the slave devices. (This is hardcoded right now but can be fixed). The actual touchpad driver is implemented in https://github.com/leo-labs/VoodooSMBus/blob/master/VoodooSMBus/ELANTouchpadDriver.hpp and this driver attaches to the device nub earlier published. 
That means, it is possible to publish a nub for the synaptic trackpad and port https://github.com/alexandred/VoodooI2CSynaptics (or probably better this: https://github.com/torvalds/linux/blob/master/drivers/input/mouse/synaptics_i2c.c) to work as an smbus slave device driver. 
I just had a quick glance at the linux source code which supported my assumptions so far.

**Comment by notthebee** [comment]
That would be amazing! If you need any data from the machine, let me know. Have Linux installed as well.

**Comment by leo-labs** [comment]
It would actually be great if the touchpad can be swapped, because the one in X1C6  is supposed to be glas and nicer

**Comment by leo-labs** [comment]
Can you contact me on gitter?

**Comment by notthebee** [comment]
You haven't been online since Monday. Should we switch to Email or some other means of contact?

**Comment by kekkokk** [comment]
> It would actually be great if the touchpad can be swapped, because the one in X1C6 is supposed to be glas and nicer

I am interested in this too. there was a reddit discussion but the guy who ordered the X1C trackpad to try to swap had never reported back if it's working.

It would be sooo nice to have the glass one

**Comment by tylernguyen** [comment]
@leo-labs I'm the owner of https://github.com/tylernguyen/x1c6-hackintosh. If you need data/info from the machine or anything else I can help you with, please let me know.

**Comment by leo-labs** [comment]
@tylernguyen Happy to offer help porting the driver from linux, however I cannot do it since I do not own an x1c6 or similar device.

**Comment by notthebee** [comment]
The X1C6 touchpad is shorter than the one from T480s. So unfortunately, they're not identical
https://imgur.com/a/CvXF5MK

**Comment by tylernguyen** [comment]
@leo-labs @notthebee I posted my Signal number on the issue in my repo. But perhaps it would advantages for us to setup a Discord to communicate and test the driver port?

**Comment by leo-labs** [comment]
I have created a gitter room for communication at https://gitter.im/VoodooSMBus/dev
