### ISSUE TITLE
Poweroff when battery shows around 5%

### ISSUE THREAD

**Issue by vistree** [leo-labs/VoodooSMBus#22]
Hi Leo,
still absolutly happy with your patch ;-)
There are a few little things a mentioned over the time:

First: when I work without power cord my battery goes down to arround 5% and then I have a poweroff instead of the t480s going to sleep or power save. It seems the battery live is not counted correctly. I am NOT absolutly sure but I think this was introduced with your VoodooSMBus kext.
Have you seen something similar?

**Comment by leo-labs** [comment]
I doubt that this is related to this driver. If you are convinced, please make sure that  this does not happen with a different touchpad driver.

**Comment by vistree** [comment]
Hello, Leo,
I use exactly the same EFI from linusyang92. Is the EFI https://github.com/leo-labs/macOS-ThinkPad-T480s still the one you are using right now? 
Can you share your config.plist (without MAC IDS) for comparison? And can we compare our BIOS settings individually?
That would be absolutely great - because the sudden shutdown is really disappointing.....

**Comment by leo-labs** [comment]
Do you still have this problem?

**Comment by vistree** [comment]
Hi Leo,
Yes, I still have this problem.

**Comment by leo-labs** [comment]
Closing this as it turned out this is not related to VoodooSMBus
