### ISSUE TITLE
Keyboard lost sometimes when switching wifi on/off in battery mode

### ISSUE THREAD

**Issue by vistree** [leo-labs/VoodooSMBus#23]
Sometime I lose my keyboard when in battery mode. I think it happens when I try to enable WIFI (e.g being in a train). I need to go to suspend - wait until the t480s sleeps - then I have to turn power on and - tada - the keyboard is back.
Any idea on this?

**Comment by leo-labs** [comment]
This never happened to me. If the touchpad still works in these cases, you should look for the problem in the keyboard driver.

**Comment by vistree** [comment]
Can you share your EFI? Maybe the VoodooPS2Driver is different from mine?

**Comment by leo-labs** [comment]
Do you still have this problem?

**Comment by vistree** [comment]
Hi Leo, yes, the problem still exists. The problem is, that I still don't know how to exactly reproduce the problem. Yesterday I removed the external keyboard, monitor and power supply - sent the notebook to suspend - and after waking it up I were still able to enter my password but then the keyboard was lost.

**Comment by leo-labs** [comment]
Can you contact me on gitter?

**Comment by vistree** [comment]
Hi Leo, I have an account on gitter now - how can I contact you there?

**Comment by leo-labs** [comment]
Closing this as it turned out this is not related to VoodooSMBus
