### ISSUE TITLE
No CPU temperature reading and no Fake SMC in the source directory

### ISSUE THREAD

**Issue by riantsoa** [leo-labs/VoodooSMBus#24]
Hi,
first I want to thank you for your effort. I was able to make my Thinkpad t480s works.
I just have one small issue, i cannot have temperature reading on the sensors on my computer.
And I looked online and I tried to find the fake SMC directory on the source code and I didn't find it. 
Please, can you advise me on what should I do?
Thank you. Very much

**Comment by leo-labs** [comment]
You should use VirtualSMC instead of FakeSMC https://github.com/acidanthera/VirtualSMC

**Comment by riantsoa** [comment]
Yes, when i look at the list of the kext loaded on the system, i see VirtualSMC already. Do you have similar issue with the temperature sensors on your t480S?

**Comment by leo-labs** [comment]
Make sure you have a current version of VirtualSMC and the sensor plugins, they are included in the release (SMCSuperIO, SMCProcessor, ...)

**Comment by riantsoa** [comment]
Thank you very much for all this information.
