### ISSUE TITLE
Cannot apply the patchers correctly at boot time

### ISSUE THREAD

**Issue by riantsoa** [leo-labs/VoodooSMBus#25]
Hi,
i was trying to install the kext and the patch  and I didn't able to make it work.
I investigate and I found this problem on the log of clover that in my opinion prevent the patch to work.
I have T480S running clover.
This is the boot log :

0:112  0:000   - [02]: com.apple.driver.AppleSMBusController (Prevent VoodooPS2Controller to attach to MOU) - invalid Find/Replace data - skipping!

And this is the line in the plist.config
<dict>
    				<key>Comment</key>
    				<string>Prevent VoodooPS2Controller to attach to MOU</string>
    				<key>Find</key>
    				<data>PHN0cmluZz5QTlAwRjBFPC9zdHJpbmc+CgkJCQk8c3RyaW5nPlBOUDBGMTM8L3N0cmluZz4JCQkJPHN0cmluZz5QTlAwRjEzPC9zdHJpbmc+</data>
    				<key>InfoPlistPatch</key>
    				<true/>
    				<key>Name</key>
    				<string>com.apple.driver.AppleSMBusController</string>
    				<key>Replace</key>
    				<data>PHN0cmluZz5QTlAwRjBFPC9zdHJpbmc+</data>
			</dict>

**Comment by riantsoa** [comment]
I resolve the issue, I moved the kext from /S/L/E to the EFI folder. Maybe it's a good idea to update the guide and specifically tell the user to use the EFI folder?

**Comment by leo-labs** [comment]
which kext did you move?

**Comment by riantsoa** [comment]
I moved the VoodooSMBus.kext from /S/L/E to clover EFI partition. It doesn't work if I put it in /S/L/E.

**Comment by leo-labs** [comment]
I think you should never put kexts into /S/L/E, rather in /L/E. Does it work there for you?

**Comment by riantsoa** [comment]
I tried also to put on /L/E. The only way to make it work for me was to move it on the clover EFI partition inside the EFI/kext/Other/ directory.

**Comment by riantsoa** [comment]
I tried also to put on /L/E. The only way to make it work for me was to move it to the clover EFI partition inside the EFI/Clover/kext/Other/ directory.

**Comment by riantsoa** [comment]
Please,On another topic on your t480s, do you have color problem and font problem?
On my t480s mojave internal screen, the windows and font is very small and I have also color problems. Do you have similar issue? Which version of macOS do you use on your t480s?
If not, is it possible you share your EFI folder? :-)
