### ISSUE TITLE
support for other OEM smbus device like HP？

### ISSUE THREAD

**Issue by Teacher-c** [leo-labs/VoodooSMBus#28]
Hi，i have a laptop which model is HP 340 G4 with a PS2 Elan touchpad , it  also has  Intel I/O Controller Hub Sunrise Point-LP (PCH) ,and id is  pci8086, 9d23. 

When i put the VoodooSMBus.kext  into the BootLoader like OC or clover, i can see  the kext is correctly be loaded through IORegistryExplorer 

<img width="1047" alt="截屏2020-04-18 10 54 10" src="https://user-images.githubusercontent.com/58407665/79626482-0d1d7080-8163-11ea-80a4-2337cacbedd6.png">

So i try to follow the Installation steps and reboot , touchpad Preferences shows correct,but the touchpad has not  response. Move the point , click, scroll, swipe etc... all gestures is not work. 
It seems that the driver did not detect the input signal at all.

<img width="669" alt="截屏2020-04-18 10 54 48" src="https://user-images.githubusercontent.com/58407665/79626488-19a1c900-8163-11ea-9e57-792fcd30bba7.png">

Can you solve this problem? 
i can  provide any debugging informations if you need for your great job

Thanks!

**Comment by leo-labs** [comment]
The existence of the SMBus device does not necessarily means that the touchpad is connected to it. Can you boot up linux and check how linux drives he touchpad? E.g. run `dmesg | grep -E 'psmouse|i801'` and past the out put here. Also please add the `i2c-dev` kernel module (`modprobe i2c-dev`), list the i2c buses `i2cdetect -l` and find the id of the smbus bus and run `i2cdetect i2c-0` where `i2c-0` is the id.

**Comment by Teacher-c** [comment]
I tried, but I have trouble in booting Linux in my laptop. So maybe I need several days to solve the problems. After that I will post the information here

**Comment by Teacher-c** [comment]
Hi, here is the info I got through linux 

******************************************************
**~$ dmesg | grep -E 'psmouse|i801'**

[    0.794502] i801_smbus 0000:00:1f.4: SPD Write Disable is set
[    0.795068] i801_smbus 0000:00:1f.4: SMBus using PCI interrupt
[    1.470033] psmouse serio1: elantech: assuming hardware version 4 (with firmware version 0x5e0f02)
[    1.486051] psmouse serio1: elantech: Synaptics capabilities query result 0x70, 0x16, 0x0a.
[    1.502366] psmouse serio1: elantech: Elan sample query result 0f, 01, a7


**~$ modprobe i2c-dev
~$ i2cdetect -l**

i2c-3	unknown   	i915 gmbus dpd                  	N/A
i2c-10	unknown   	Radeon i2c bit bus 0x96         	N/A
i2c-1	unknown   	i915 gmbus dpc                  	N/A
i2c-8	unknown   	Radeon i2c bit bus 0x94         	N/A
i2c-6	unknown   	Radeon i2c bit bus 0x92         	N/A
i2c-13	unknown   	DPDDC-C                         	N/A
i2c-4	unknown   	Radeon i2c bit bus 0x90         	N/A
i2c-11	unknown   	Radeon i2c bit bus 0x97         	N/A
i2c-2	unknown   	i915 gmbus dpb                  	N/A
i2c-0	unknown   	SMBus I801 adapter at 5040      	N/A
i2c-9	unknown   	Radeon i2c bit bus 0x95         	N/A
i2c-7	unknown   	Radeon i2c bit bus 0x93         	N/A
i2c-5	unknown   	Radeon i2c bit bus 0x91         	N/A
i2c-12	unknown   	DPDDC-A                         	N/A


**~$ i2cdetect i2c-0**
Error: I2C bus name doesn't match any bus present!
Usage: i2cdetect [-y] [-a] [-q|-r] I2CBUS [FIRST LAST]
       i2cdetect -F I2CBUS
       i2cdetect -l
  I2CBUS is an integer or an I2C bus name
  If provided, FIRST and LAST limit the probing range.

************************************************************

Is it indicated that the touchpad is not connected to the smbus?

**Comment by Teacher-c** [comment]
And I want to  know  "psmouse serio1: elantech: Synaptics capabilities query result 0x70, 0x16, 0x0a."  means for what?

**Comment by leo-labs** [comment]
Can you try `i2cdetect 0` ?

**Comment by Teacher-c** [comment]
Yes,and it shows :

WARNING! This program can confuse your I2C bus, cause data loss and worse!
I will probe file /dev/i2c-0.
I will probe address range 0x03-0x77.
Continue? [Y/n] y
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- 08 -- -- -- -- -- -- -- 
10: -- -- -- -- -- 15 -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: 30 -- -- -- -- 35 36 -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- 44 -- -- -- -- -- -- -- -- -- -- -- 
50: 50 -- 52 -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- 77

**Comment by leo-labs** [comment]
Sorry, I don't think that your touchpad has an intertouch companion on the SMBus and Linux is not using the SMBus for the touchpad but just PS2. I might be wrong, so let me know if you find out that linux or windows touchpad drivers are using the SMBus.
