### ISSUE TITLE
Touchpad dead after reboot

### ISSUE THREAD

**Issue by vistree** [leo-labs/VoodooSMBus#4]
Hi Leo,
thanx for your work! Really like your approach.
I tried to install your kext this morning but unfortunatelly, the touchpad is not working after reboot.
- I added your patch to the END of KernelToPatch section in my config.list (The same section the other for patches from linusyang92 are - I'm using his EFI).
- Removed VoodooPS2Mouse
- Afterwards I copied your kext to /L/E and cleared the kextcache (sudo kextcache -i /) 
- Rebooted
but now my touchpad is not working any more.

Questions:
- is /L/E the correct location or is it better to copy your kext to EFI folder?
- gokula provides an SSDT-SMBUS.dsl, do we need something like this?
- what about AppleIntelLpssiI2C.kext and AppleIntelLpssiI2CController.kext, do they need to be manually deleted from system or can they stay in place?

Kind regards
     Kai

**Comment by leo-labs** [comment]
* I haven't tested it with /L/E, I would have thought it works, but currently I have it in my EFI directory.
* I use the same EFI as you do; There was already an SSDT-SMBUS.dsl and with that it works fine, the one from gokula should not be neccessary. 
* About AppleIntelLpssI2C: I wrote a dummy driver to replace those, so we would not need to delete them. Can you send me your ioreg output for the I2C0 device and the SBUS device?

**Comment by vistree** [comment]
I will first try to fix it by replacing some stuff I copied from gokula. Which SSDT-KDB.dsl from linusyang92 do you use? The one for the VoodooPS2 kext or the one for the ApplePS2SmartTouchPad?

**Comment by vistree** [comment]
And - did you disable anything keyboard/mouse related in the BIOS? Like the trackpoint?

**Comment by leo-labs** [comment]
I use the `SSDT-KDB.dsl`  for VoodooPS2. Of course you also need to remove the `ApplePS2SmartTouchPad` kext. Trackpoint is currently disabled, but it should not matter.

**Comment by vistree** [comment]
Thanx leo, Trackpad is working now. I moved the kext to EFI which solved my problem. Most of the stuff is running fine. But, I have one main problem also with your kext: if I type a while on the internal keyboard, then the cursor jumps to a different position in the text - and I start writing at the wrong position. Do you see the same problem on your mashine? It seems that the touchpad is to sensitive and pressing the keyboard keys seems sometimes to generate a mouse click??!

**Comment by vistree** [comment]
Just recognised that you already cover the jumping curson in issue #2

**Comment by leo-labs** [comment]
Yes, it is not a problem with the touchpad being too sensitive but the missing palm detection and disable-while-typing functionality. In linux this is e.g. realized with libinput or similar libraries. I hope that this can be implemented in the multitouch interface, and not just  in this driver. This is my next project, as soon as I have time to work on this driver.

**Comment by leo-labs** [comment]
Please check the new version :)

**Comment by vistree** [comment]
Yes, works really smooth now. First time I can use my trackpad AND trackpoint without keyboard typing issues!!
