### ISSUE TITLE
other model issue (ThinkPad P52)

### ISSUE THREAD

**Issue by liuyishengalan** [leo-labs/VoodooSMBus#8]
As long as the next installed following by your installation instructions, the trackpoint, trackpad and keyboard all not working

(ThinkPad P52, PCH SMBUS 8086-A323)

**Comment by leo-labs** [comment]
Please try to replace the value in this line https://github.com/leo-labs/VoodooSMBus/blob/master/VoodooSMBus/Info.plist#L30 with `0xa3238086`. For further debugging, please identify the smbus device in ioreg and check what attaches to it.

**Comment by liuyishengalan** [comment]
That is extremely amazing, all works well. Thanks for what you have achieved so far.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by leo-labs** [comment]
This is also great to hear for me as well! I am going to include your smbus device in the repository, so you can easily update in the future! Do you know of any other models with an ELAN smbus trackpad?  And does the trackpoint also work?

**Comment by liuyishengalan** [comment]
so far, I just know P52, P72 and T480s
________________________________

**Comment by leo-labs** [comment]
Do you know if it is the same smbus controller in P72 or a different one?

**Comment by liuyishengalan** [comment]
not sure yet
________________________________

**Comment by liuyishengalan** [comment]
We are testing a new model, ThinkPad yoga260,
This model has same PCH PID & PID as T480s.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by leo-labs** [comment]
Did it work?
